repos:
- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    args: [--in-place, --verbose]
    additional_dependencies: [toml] # TODO: Remove when yapf is upgraded
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.5
  hooks:
  - id: ruff
    args: [--output-format, github]
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    exclude: 'benchmarks/sonnet.txt|(build|tests/(lora/data|models/fixtures|prompts))/.*'
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.5
  hooks:
  - id: clang-format
    exclude: 'csrc/(moe/topk_softmax_kernels.cu|quantization/gguf/(ggml-common.h|dequantize.cuh|vecdotq.cuh|mmq.cuh|mmvq.cuh))'
    types_or: [c++, cuda]
    args: [--style=file, --verbose]
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.27
  hooks:
  - id: pymarkdown
    files: docs/.*
- repo: local
  hooks:
  - id: mypy # TODO: Use https://github.com/pre-commit/mirrors-mypy when mypy setup is less awkward
    name: run mypy
    entry: tools/mypy.sh 1
    language: python
    additional_dependencies: [mypy==1.11.1, types-setuptools, types-PyYAML, types-requests]
    pass_filenames: false
  - id: shellcheck
    name: Lint shell scripts
    entry: tools/shellcheck.sh
    language: script
  - id: png-lint
    name: Lint PNG exports from excalidraw
    entry: tools/png-lint.sh
    language: script
    types: [png]
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.6
  hooks:
  - id: actionlint
