name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.12"
    - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
    - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      id: pre-commit
      continue-on-error: true
      with:
        extra_args: --all-files --hook-stage manual
    outputs:
      status: ${{ steps.pre-commit.outcome }}
  update-label:
    needs: pre-commit
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Add `pre-commit-passed` if success
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: needs.pre-commit.outputs.status == 'success'
      with:
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['pre-commit-passed']
          })
    - name: Remove `pre-commit-passed` otherwise
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: needs.pre-commit.outputs.status != 'success'
      with:
        script: |
          try {
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'pre-commit-passed'
            })
          } catch (e) {
            // Label might not exist, which is fine
            if (e.status !== 404) {
              throw e;
            }
          }
