name: Publish Helm chart on Github Registry

# Configures this workflow to run every time a change is pushed to the branch called `main`.
on:
  push:
    branches:
      - main
  pull_request:
env:
  CHART_NAME: vllm-helm-chart

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v4.2.0

      - name: helm login
        run:  echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin

      - name: get helm chart version
        run:  IMAGE_TAG="$(helm show chart . | awk '/version/ {print $2}')"

      - name: helm package
        run:  helm package examples/online_serving/chart-helm --version $IMAGE_TAG

      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run:  helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository_owner }}